# Generated by Django 4.1.6 on 2023-03-09 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyTaller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuesto',
            name='estado',
            field=models.CharField(choices=[('1', 'Abonado'), ('0', 'Impago')], max_length=2),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='fpago',
            field=models.CharField(choices=[('0', 'Débito'), ('1', 'Crédito'), ('2', 'Transferencia'), ('3', 'Efectivo')], max_length=2),
        ),
    ]
