# Generated by Django 4.1.6 on 2023-03-09 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyTaller', '0002_alter_presupuesto_estado_alter_presupuesto_fpago'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mecanicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('nacimiento', models.DateField()),
                ('mail', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
