# Generated by Django 4.1.6 on 2023-03-09 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyTaller', '0003_mecanicos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mecanicos',
            name='password',
        ),
    ]
